name: Enterprise Security Gate
on:
  push:
    branches: [ feature/enterprise-pipeline ] 
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  job_lint_bash:
    name: ShellCheck (Bash Lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  job_sast_python:
    name: Bandit (Python SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  
      
      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit
        run: bandit -r 01-ssl-scanner-service/app/ -ll  
  
  job_lint_docker:
    name: Hadolint (Docker Lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: 01-ssl-scanner-service/app/Dockerfile
  job_lint_ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible Lint and Dependencies
        run: |
          pip install ansible-lint
          ansible-galaxy collection install community.general
      - name: Run Ansible-Lint
        run: ansible-lint 03-observability-management/ansible/hardering.yml